resolver: lts-22.6

packages:
- kubernetes
- kubernetes-client

extra-deps:
- oidc-client-0.7.0.1@sha256:557341f7521e62c09abddf0d06c8e8acce119d3a9a4c4ffac1ab8ca3fc0e5067,3382

# - git: https://github.com/codedownio/haskell-oidc-client
#   commit: 3cb40ba3abfc9a030f31cc2f919bfc192f7e9f5e
