on: [push]
name: CI
jobs:
  cabal:
    name: Cabal / GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
        - "8.10.7"
        - "9.0.2"
        - "9.2.8"
        - "9.4.8"
        - "9.6.5"
        - "9.8.2"
        # k8s_release:
        # # Choose a subset of these to ease the load on CI
        # - "1.25"
        # - "1.26"
        # - "1.27"
        # - "1.28"
        # - "1.29"
        # - "1.30"
    steps:
    - uses: actions/checkout@v4
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.compiler.ghc }}
        cabal-version: '3.8.1.0'
    - run: cabal build all --enable-tests
    - run: cabal test all

  stack:
    name: Stack / Kubernetes ${{ matrix.k8s_release }} / GHC ${{ matrix.compiler.ghc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - ghc: "8.10.7"
          yaml: "stack-8.10.7.yaml"
        - ghc: "9.0.2"
          yaml: "stack-9.0.2-aeson1.yaml"
        - ghc: "9.0.2"
          yaml: "stack-9.0.2-aeson2.yaml"
        - ghc: "9.2.8"
          yaml: "stack-9.2.8.yaml"
        - ghc: "9.4.8"
          yaml: "stack-9.4.8.yaml"
        - ghc: "9.6.5"
          yaml: "stack-9.6.5.yaml"
        - ghc: "9.8.2"
          yaml: "stack.yaml"
        k8s_release:
        # Choose a subset of these to ease the load on CI
        - "1.25"
        - "1.26"
        - "1.27"
        - "1.28"
        - "1.29"
        - "1.30"
    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.compiler.ghc }}
        enable-stack: true
        stack-version: "latest"

    - uses: actions/cache@v4
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.compiler.ghc }}-${{ matrix.compiler.yaml }}

    - name: Build
      run: |
        nix run .#set-stack-version -- "${{matrix.k8s_release}}" "${{matrix.compiler.yaml}}"

        stack build --stack-yaml ${{matrix.compiler.yaml}} --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --stack-yaml ${{matrix.compiler.yaml}} --system-ghc
